package tw.avianjay.airplaydroid.protocol.fairplay

import org.junit.jupiter.api.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Golden-vector conformance for the transcribed [FairPlaySapCore].
 *
 * The fixtures in `src/test/resources/fairplay/` are copied byte-for-byte from
 * the `objevovat` project's `conformance/` directory:
 *
 *   https://github.com/objevovat/fairplay-sap-core-airplay2-sender-authentication-handshake
 *
 * They are language-independent numbers generated by a *separate* program
 * (`fpsapcore`), so passing them is evidence about this port rather than a
 * restatement of it. The upstream README is explicit that a validator sharing
 * an implementation with the thing it validates proves nothing, which is why
 * these expected values are read from CSV and never recomputed here.
 *
 * CSV layout (both files carry a leading `#` comment line naming the columns):
 *
 *   sap_hash.csv     `block(64 bytes hex),sapHash(16 bytes hex)`        40 rows
 *   bridge_x9head.csv `localSAP(128 hex),gp(128 hex),x9head(20 hex)`    30 rows
 *
 * Both tests assert the *full* row count passes; the per-row pass count is
 * printed so a partial failure is legible in the test output.
 */
class FairPlaySapCoreGoldenTest {

    private fun hex(s: String): ByteArray {
        val t = s.trim()
        require(t.length % 2 == 0) { "odd-length hex: ${t.length}" }
        return ByteArray(t.length / 2) { t.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
    }

    private fun toHex(b: ByteArray): String =
        b.joinToString("") { "%02x".format(it.toInt() and 0xFF) }

    /** Reads a classpath CSV, dropping blanks and `#` comments. */
    private fun readRows(resource: String): List<List<String>> {
        val stream = javaClass.getResourceAsStream(resource)
        assertNotNull(stream, "missing test resource $resource")
        val lines = stream.bufferedReader().use { it.readLines() }
        println("--- $resource : ${lines.size} raw lines, first 3 ---")
        lines.take(3).forEach { println("    $it") }
        return lines
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") }
            .map { it.split(",").map(String::trim) }
    }

    /**
     * Every row of `sap_hash.csv` through [FairPlaySapCore.sapHash].
     *
     * Row 0 (all-zero block) is a smoke test that passes even with a wrong ring
     * table, so the assertion is on the whole corpus, not on that row.
     */
    @Test
    fun sapHashMatchesEveryGoldenVector() {
        val rows = readRows("/fairplay/sap_hash.csv")
        assertEquals(40, rows.size, "expected 40 sap_hash vectors")

        var passed = 0
        val failures = mutableListOf<String>()

        for ((i, row) in rows.withIndex()) {
            assertEquals(2, row.size, "row $i: expected 2 columns, got ${row.size}")
            val block = hex(row[0])
            val expected = hex(row[1])
            assertEquals(64, block.size, "row $i: block must be 64 bytes")
            assertEquals(16, expected.size, "row $i: sapHash must be 16 bytes")

            val actual = FairPlaySapCore.sapHash(block)
            if (actual.contentEquals(expected)) {
                passed++
            } else {
                failures += "row $i: expected ${toHex(expected)} actual ${toHex(actual)}"
            }
        }

        println("sap_hash PASS COUNT: $passed/${rows.size}")
        failures.take(5).forEach { println("  FAIL $it") }
        assertTrue(failures.isEmpty(), "sap_hash ${passed}/${rows.size} passed; ${failures.size} failed:\n" +
            failures.take(5).joinToString("\n"))
        assertEquals(rows.size, passed)
    }

    /**
     * Every row of `bridge_x9head.csv` through
     * [FairPlaySapCore.bridgeX9HeadForSap]. Passing this means the port is a
     * complete Phase-1 bridge, not just a SAP hash.
     */
    @Test
    fun bridgeX9HeadMatchesEveryGoldenVector() {
        val rows = readRows("/fairplay/bridge_x9head.csv")
        assertEquals(30, rows.size, "expected 30 bridge_x9head vectors")

        var passed = 0
        val failures = mutableListOf<String>()

        for ((i, row) in rows.withIndex()) {
            assertEquals(3, row.size, "row $i: expected 3 columns, got ${row.size}")
            val localSap = hex(row[0])
            val gp = hex(row[1])
            val expected = hex(row[2])
            assertEquals(128, localSap.size, "row $i: localSap must be 128 bytes")
            assertEquals(128, gp.size, "row $i: gp must be 128 bytes")
            assertEquals(20, expected.size, "row $i: x9head must be 20 bytes")

            val actual = FairPlaySapCore.bridgeX9HeadForSap(localSap, gp)
            if (actual.contentEquals(expected)) {
                passed++
            } else {
                failures += "row $i: expected ${toHex(expected)} actual ${toHex(actual)}"
            }
        }

        println("bridge_x9head PASS COUNT: $passed/${rows.size}")
        failures.take(5).forEach { println("  FAIL $it") }
        assertTrue(failures.isEmpty(), "bridge_x9head ${passed}/${rows.size} passed; ${failures.size} failed:\n" +
            failures.take(5).joinToString("\n"))
        assertEquals(rows.size, passed)
    }

    /**
     * The unsigned-underflow trap, pinned directly against the first entries of
     * the upstream `ring_indices.csv`. A port that derives these with signed
     * Int gets -155 at i=0 and 55 from naive modular reasoning; both are wrong.
     */
    @Test
    fun ringIndicesReproduceTheDocumentedUnderflow() {
        val ring = FairPlaySapCore.buildRingIndices()
        assertEquals(4, ring.size)
        ring.forEach { assertEquals(840, it.size) }

        // Documented in conformance/README.md, measured in six languages.
        assertEquals(101, ring[0][0], "x[0] must wrap through UInt, not give 55 or -155")
        assertEquals(199, ring[1][0])
        assertEquals(33, ring[2][0])
        assertEquals(0, ring[3][0])
        assertEquals(45, ring[0][154])
        assertEquals(0, ring[0][155], "sequences agree from i=155 onward")
    }

    /** `rotateOrZero` is not a rotate: a zero count yields 0, not the input. */
    @Test
    fun rotateOrZeroReturnsZeroForZeroCount() {
        assertEquals(0, FairPlaySapCore.rotateOrZero(0xAB, 0))
        assertEquals(0x57, FairPlaySapCore.rotateOrZero(0xAB, 1))
    }
}
